//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaFiscalSP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="NotaFiscalSP.LoteNFeSoap")]
    public interface LoteNFeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.EnvioRPSResponse> EnvioRPSAsync(NotaFiscalSP.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.EnvioLoteRPSResponse> EnvioLoteRPSAsync(NotaFiscalSP.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(NotaFiscalSP.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.CancelamentoNFeResponse> CancelamentoNFeAsync(NotaFiscalSP.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeResponse> ConsultaNFeAsync(NotaFiscalSP.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(NotaFiscalSP.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(NotaFiscalSP.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaLoteResponse> ConsultaLoteAsync(NotaFiscalSP.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(NotaFiscalSP.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaCNPJResponse> ConsultaCNPJAsync(NotaFiscalSP.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequest()
        {
        }
        
        public EnvioRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponse()
        {
        }
        
        public EnvioRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequest()
        {
        }
        
        public EnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class EnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponse()
        {
        }
        
        public EnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequest()
        {
        }
        
        public TesteEnvioLoteRPSRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TesteEnvioLoteRPSResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class TesteEnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponse()
        {
        }
        
        public TesteEnvioLoteRPSResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequest()
        {
        }
        
        public CancelamentoNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelamentoNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class CancelamentoNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponse()
        {
        }
        
        public CancelamentoNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequest()
        {
        }
        
        public ConsultaNFeRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponse()
        {
        }
        
        public ConsultaNFeResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequest()
        {
        }
        
        public ConsultaNFeRecebidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeRecebidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeRecebidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponse()
        {
        }
        
        public ConsultaNFeRecebidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequest()
        {
        }
        
        public ConsultaNFeEmitidasRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaNFeEmitidasResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaNFeEmitidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponse()
        {
        }
        
        public ConsultaNFeEmitidasResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequest()
        {
        }
        
        public ConsultaLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponse()
        {
        }
        
        public ConsultaLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequest()
        {
        }
        
        public ConsultaInformacoesLoteRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformacoesLoteResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaInformacoesLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponse()
        {
        }
        
        public ConsultaInformacoesLoteResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJRequest", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public int VersaoSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequest()
        {
        }
        
        public ConsultaCNPJRequest(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCNPJResponse", WrapperNamespace="http://www.prefeitura.sp.gov.br/nfe", IsWrapped=true)]
    public partial class ConsultaCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponse()
        {
        }
        
        public ConsultaCNPJResponse(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface LoteNFeSoapChannel : NotaFiscalSP.LoteNFeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<NotaFiscalSP.LoteNFeSoap>, NotaFiscalSP.LoteNFeSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), LoteNFeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.EnvioRPSResponse> NotaFiscalSP.LoteNFeSoap.EnvioRPSAsync(NotaFiscalSP.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.EnvioRPSResponse> EnvioRPSAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.EnvioRPSRequest inValue = new NotaFiscalSP.EnvioRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).EnvioRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.EnvioLoteRPSResponse> NotaFiscalSP.LoteNFeSoap.EnvioLoteRPSAsync(NotaFiscalSP.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.EnvioLoteRPSResponse> EnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.EnvioLoteRPSRequest inValue = new NotaFiscalSP.EnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).EnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.TesteEnvioLoteRPSResponse> NotaFiscalSP.LoteNFeSoap.TesteEnvioLoteRPSAsync(NotaFiscalSP.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.TesteEnvioLoteRPSRequest inValue = new NotaFiscalSP.TesteEnvioLoteRPSRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).TesteEnvioLoteRPSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.CancelamentoNFeResponse> NotaFiscalSP.LoteNFeSoap.CancelamentoNFeAsync(NotaFiscalSP.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.CancelamentoNFeResponse> CancelamentoNFeAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.CancelamentoNFeRequest inValue = new NotaFiscalSP.CancelamentoNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).CancelamentoNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeResponse> NotaFiscalSP.LoteNFeSoap.ConsultaNFeAsync(NotaFiscalSP.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeResponse> ConsultaNFeAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaNFeRequest inValue = new NotaFiscalSP.ConsultaNFeRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaNFeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeRecebidasResponse> NotaFiscalSP.LoteNFeSoap.ConsultaNFeRecebidasAsync(NotaFiscalSP.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaNFeRecebidasRequest inValue = new NotaFiscalSP.ConsultaNFeRecebidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaNFeRecebidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeEmitidasResponse> NotaFiscalSP.LoteNFeSoap.ConsultaNFeEmitidasAsync(NotaFiscalSP.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaNFeEmitidasRequest inValue = new NotaFiscalSP.ConsultaNFeEmitidasRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaNFeEmitidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaLoteResponse> NotaFiscalSP.LoteNFeSoap.ConsultaLoteAsync(NotaFiscalSP.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaLoteResponse> ConsultaLoteAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaLoteRequest inValue = new NotaFiscalSP.ConsultaLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaInformacoesLoteResponse> NotaFiscalSP.LoteNFeSoap.ConsultaInformacoesLoteAsync(NotaFiscalSP.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaInformacoesLoteRequest inValue = new NotaFiscalSP.ConsultaInformacoesLoteRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaInformacoesLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NotaFiscalSP.ConsultaCNPJResponse> NotaFiscalSP.LoteNFeSoap.ConsultaCNPJAsync(NotaFiscalSP.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotaFiscalSP.ConsultaCNPJResponse> ConsultaCNPJAsync(int VersaoSchema, string MensagemXML)
        {
            NotaFiscalSP.ConsultaCNPJRequest inValue = new NotaFiscalSP.ConsultaCNPJRequest();
            inValue.VersaoSchema = VersaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((NotaFiscalSP.LoteNFeSoap)(this)).ConsultaCNPJAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LoteNFeSoap,
            
            LoteNFeSoap12,
        }
    }
}
